pairs(swiss)
cor(swiss)
boxplot(swiss)
hist(swiss$Catholic)
plot(swiss$Examination, swiss$Fertility)
plot(swiss$Infant.Mortality, swiss$Fertility)
fit = lm(Formula =Fertility-Examination+Infant.Mortality,data-swiss)
summary(fit)
confint(fit)
model.matrix(fit)
plot(swiss$Examination,rstandard(fit))
plot(swiss$Infant.Mortality, rstandard(fit))
plot(fitted(fit),rstandard(fit))
plot(fitted(fit),rstandard(fit))
identity(fitted(fit), rstandard(fit), labels...)
qqnorm(rstandard(fit))
qqline(rstandard(fit))
plot(cooks.distance(fit))
p <- dim(model.matrix(fit))[2]
n <- dim(model.matrix(fit))[1]
abline(8/(n-2*p),0)
identity(cooks.distance(fit),label...)
plot(hatvalue(fit))
abline(2*p/n,0)
identity(hatvalues(fit), labels....)
plot(swiss$Examination,swiss$Fertility)
text(swiss$Examination[19], swiss$Fertility[19], rownames(swiss)[19])
plot(swiss$Infant,Mortality,swiss$Fertility)
test(swiss$Infant.Mortality[19],swiss$Fertility[19], rownames...)
swiss2 = swiss[-19,]
fit2 = lm(Fertility-Examination_Infant.Mortality,data-swiss)
summary(fit2)
confint(fit2)